### ISSUE TITLE
Instagram detect login as souspicious

### ISSUE THREAD

**Issue by hostyn** [Gumbraise/instagram-bomber#19]
Can't login

**Comment by Gumbraise** [comment]
Hi. Can you show me the error that you receive please.
Thanks

**Comment by hostyn** [comment]
```
Got Password. Attempting to login.

Request return 400 error!

Whoops. Couldn't login. Check the above flags to know more.

A critical error happened. Please make sure that you executed all commands properly and relaunch the program.
```
When I log into a browser, Instagram tells me that suspicious activity has been detected.

**Comment by Gumbraise** [comment]
Did you set a proxy on ? Are you connected with a VPN ? Are you on the same machine or on another like a VPS ?

**Comment by hostyn** [comment]
No proxy, no VPN, running in a virtual machine with ubuntu.

**Comment by Gumbraise** [comment]
Okay. Try to connect you with another Instagram account. If it works, it's a problem coming from your Instagram account. In this case, try to disable the A2F if it is enable or try to be in LTE when you log in. Else, it's a problem with your internet connexion or your firewall. In this case, try to be in LTE with your phone and make a personal hotspot or try with Terminus directly on the phone.
