### ISSUE TITLE
So is there's a limit by Instagram

### ISSUE THREAD

**Issue by Mahatma00Gandhi** [Gumbraise/instagram-bomber#24]
Obviously Instagram probably has some limit about spams but how much do you think ? 

Also does it change if we are using links or not links and other factors ?

**Comment by Gumbraise** [comment]
Hey, I know that Instagram "bans" me from 200 messages. Sometimes it's less, sometimes it's more. But if you want an average it's 200.
I don't think that send links in messages change anything.
