### ISSUE TITLE
Feature request: Send dm from multiple account

### ISSUE THREAD

**Issue by lilcsz** [Gumbraise/instagram-bomber#3]
I want to send dm from multiple account
ex: using accounts on list.txt

**Comment by lilcsz** [comment]
btw i fixed the codes https://github.com/Gumbraise/instagram-bomber/pull/2

**Comment by abdelich** [comment]
has no attribute "sendMessage"

**Comment by lilcsz** [comment]
@abdelich Can you send me full error code?

**Comment by Gumbraise** [comment]
> 
> 
> has no attribute "sendMessage"

Before launch ``bomber.py`` please execute ``pip install InstagramAPI``
