### ISSUE TITLE
instagram api error

### ISSUE THREAD

**Issue by abdelich** [Gumbraise/instagram-bomber#4]
instagram api error dont have "sendMessage" attribute

**Comment by lilcsz** [comment]
It's weird, try this:
pip uninstall
pip install InstagramAPI 
or:
pip3 uninstall
pip3 install InstagramAPI 

Note: be sure you added InstagramAPI.py file into Program Files\Python\Python36-32\Lib\site-packages\InstagramAPI

**Comment by lilcsz** [comment]
If still you get error reinstall python and install python3.8.3 version

**Comment by Gumbraise** [comment]
That's normal. Is because InstagramAPI via pip doesn't have sendMessage attribute. So add it manually with the InstagramAPI.py in the code
