### ISSUE TITLE
not able to instaa

### ISSUE THREAD

**Issue by akjankit** [Gumbraise/instagram-bomber#5]
hey i am kind of new here . can u make a tutorial video that will help me and many peoples because i am not able to install.

**Comment by lilcsz** [comment]
Can i help you? Send me error

**Comment by Gumbraise** [comment]
> 
> 
> hey i am kind of new here . can u make a tutorial video that will help me and many peoples because i am not able to install.

I will when my computer will be repaired :)

**Comment by LX5321** [comment]
> hey i am kind of new here . can u make a tutorial video that will help me and many peoples because i am not able to install.

Download and unpack the zip file. Then run the command to install the requirements as given in the `readme.md`. After that run `python3 bomber.py` in the directory.

**Comment by LX5321** [comment]
> > hey i am kind of new here . can u make a tutorial video that will help me and many peoples because i am not able to install.
> 
> I will when my computer will be repaired :)

It works for me. Just tried. Thanks a bunch :+1:

**Comment by avtarsingh101** [comment]
how do i do this on mac

**Comment by LX5321** [comment]
> how do i do this on mac
#5

**Comment by Gumbraise** [comment]
> 
> 
> how do i do this on mac

Same

**Comment by Gumbraise** [comment]
Hello, I made a video with all the commands for those who had not succeeded: https://youtu.be/PJ0wkxsS-uM
Thanks
